// AUTO-GENERATED by scripts/generate-assets-registry.mjs — do not edit by hand.
// Source of truth: assets/manifests/assets-manifest.json (v1.0.0, 77 assets).

export type AssetId =
  | "state_card_holographic_de_notifications_neon"
  | "ui_card_holographic_de_security_cyberpunk"
  | "device_card_holographic_des_connected_devices"
  | "scene_command_center_holographic_futuristic"
  | "capability_cur_energy_holographic_futuristic"
  | "device_emblem_cyberpunk_du_laptop_holographic"
  | "agent_emblem_de_cybersecurity_holographic"
  | "voice_emblem_futuristic_d_assistant_voice_neon"
  | "state_emblem_holographic_cyberpunk_en_pause"
  | "state_emblem_holographic_d_alert_futuristic"
  | "device_emblem_holographic_de_camera_cybernetique"
  | "agent_emblem_holographic_de_communication_ia"
  | "memory_emblem_holographic_de_control_ia"
  | "agent_emblem_holographic_de_creation_futuristic"
  | "device_emblem_holographic_de_smart_home"
  | "voice_emblem_holographic_de_microphonephone_neon"
  | "agent_emblem_holographic_de_protection_cybernetique"
  | "state_emblem_holographic_de_download_futuristic"
  | "state_emblem_holographic_de_upload_cyberpunk"
  | "state_emblem_holographic_de_verification_futuristic"
  | "device_emblem_holographic_du_sensor_futuristic"
  | "memory_emblem_holographic_du_core_memory_ia"
  | "device_emblem_holographic_du_desktop_cyberpunk"
  | "state_emblem_holographic_du_power_neon"
  | "memory_emblem_neon_d_analysis_spatial"
  | "capability_emblem_neon_d_automation_futuristic"
  | "state_emblem_neon_de_sync_futuristic"
  | "core_emblem_orbital_quantum_lumineux"
  | "device_emblem_satellite_holographic_futuristic"
  | "device_emblem_smartphone_orbital_neon_futuristic"
  | "core_globe_holographic_neon_futuristic"
  | "scene_hangar_futuristic_de_drones_en_orbit"
  | "voice_icon_holographic_de_microphone_permission"
  | "scene_secure_data_vault_environment"
  | "ui_interface_de_research_futuristic_jarvis_x2"
  | "state_interface_holographic_d_approval_futuristic"
  | "ui_interface_holographic_de_secure_vault"
  | "ui_interface_holographic_focus_deep_work"
  | "ui_interface_holographic_jarvis_x2"
  | "memory_interface_holographic_knowledge_futuristic"
  | "capability_jarvis_x2_local_ai_futuristic"
  | "device_wearable_holographic_futuristic"
  | "scene_metropolis_cyberpunk_flottante_neon"
  | "core_nexus_cosmic_holographic_neon"
  | "core_nexus_holographic_orbital_futuristic"
  | "scene_nexus_energy_futuristic_en_orbit"
  | "voice_core_d_energy_audio_futuristic_symmetric"
  | "core_d_energy_holographic_futuristic"
  | "memory_core_de_data_holographic_futuristic"
  | "core_holographic_d_energy_futuristic"
  | "core_nebula_d_energy_cosmic_neon"
  | "device_nud_quantum_iot_en_orbit"
  | "voice_orbe_d_alert_voicee_cybernetique"
  | "memory_orbe_holographic_d_ai"
  | "core_orbe_hud_futuristic_neon_sur_transparence"
  | "core_orbe_energy_holographic_futuristic"
  | "state_panel_hud_futuristic_de_task_progress"
  | "scene_platform_energy_futuristic_en_levitation"
  | "scene_command_bridge_spatial_holographic"
  | "scene_portal_cosmic_futuristic_aux_crystals_lumineux"
  | "core_portal_holographic_neon_symmetric"
  | "capability_portal_energy_futuristic_bleu_et_violet"
  | "scene_reactor_holographic_futuristic_en_levitation"
  | "memory_holographic_network_d_ai"
  | "memory_neural_network_holographic_neon"
  | "scene_vr_lounge_futuristic_holographic_luxueux"
  | "capability_sphere_holographic_de_management_documents"
  | "ui_dashboard_d_automation_futuristic"
  | "ui_dashboard_futuristic_jarvis_x2"
  | "ui_dashboard_holographic_analytics"
  | "ui_dashboard_holographic_des_active_agents"
  | "ui_dashboard_holographic_des_documents"
  | "ui_dashboard_holographic_jarvis_x2"
  | "memory_dashboard_holographic_memory_connectee"
  | "ui_dashboard_jarvis_x2_dev_studio"
  | "capability_tableau_de_navigation_holographic_futuristic"
  | "capability_tableau_weather_futuristic_de_location";

export interface AssetEntry {
  id: AssetId;
  category: string;
  png: string;
  webp: string;
  thumbnail: string;
  width: number;
  height: number;
  hasAlpha: boolean;
  grade: "A" | "B" | "C";
  status: "approved" | "review";
  tags: string[];
  issues: string[];
}

export const ASSET_REGISTRY: Record<AssetId, AssetEntry> = {
  "state_card_holographic_de_notifications_neon": {
    "id": "state_card_holographic_de_notifications_neon",
    "category": "08-actions-states",
    "png": "/assets/production/08-actions-states/state_card_holographic_de_notifications_neon.png",
    "webp": "/assets/web/08-actions-states/state_card_holographic_de_notifications_neon.webp",
    "thumbnail": "/assets/thumbnails/08-actions-states/state_card_holographic_de_notifications_neon.webp",
    "width": 1024,
    "height": 1536,
    "hasAlpha": false,
    "grade": "B",
    "status": "review",
    "tags": [
      "state",
      "action",
      "status"
    ],
    "issues": [
      "opaque background; use as scene/card, not floating asset"
    ]
  },
  "ui_card_holographic_de_security_cyberpunk": {
    "id": "ui_card_holographic_de_security_cyberpunk",
    "category": "03-product-ui",
    "png": "/assets/production/03-product-ui/ui_card_holographic_de_security_cyberpunk.png",
    "webp": "/assets/web/03-product-ui/ui_card_holographic_de_security_cyberpunk.webp",
    "thumbnail": "/assets/thumbnails/03-product-ui/ui_card_holographic_de_security_cyberpunk.webp",
    "width": 1024,
    "height": 1536,
    "hasAlpha": true,
    "grade": "B",
    "status": "review",
    "tags": [
      "ui",
      "dashboard",
      "product"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "device_card_holographic_des_connected_devices": {
    "id": "device_card_holographic_des_connected_devices",
    "category": "07-physical-world",
    "png": "/assets/production/07-physical-world/device_card_holographic_des_connected_devices.png",
    "webp": "/assets/web/07-physical-world/device_card_holographic_des_connected_devices.webp",
    "thumbnail": "/assets/thumbnails/07-physical-world/device_card_holographic_des_connected_devices.webp",
    "width": 1024,
    "height": 1536,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "device",
      "physical-world",
      "connected"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "scene_command_center_holographic_futuristic": {
    "id": "scene_command_center_holographic_futuristic",
    "category": "09-cinematic-environments",
    "png": "/assets/production/09-cinematic-environments/scene_command_center_holographic_futuristic.png",
    "webp": "/assets/web/09-cinematic-environments/scene_command_center_holographic_futuristic.webp",
    "thumbnail": "/assets/thumbnails/09-cinematic-environments/scene_command_center_holographic_futuristic.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "cinematic",
      "environment",
      "scene"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "capability_cur_energy_holographic_futuristic": {
    "id": "capability_cur_energy_holographic_futuristic",
    "category": "02-system-capabilities",
    "png": "/assets/production/02-system-capabilities/capability_cur_energy_holographic_futuristic.png",
    "webp": "/assets/web/02-system-capabilities/capability_cur_energy_holographic_futuristic.webp",
    "thumbnail": "/assets/thumbnails/02-system-capabilities/capability_cur_energy_holographic_futuristic.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "system",
      "general"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "device_emblem_cyberpunk_du_laptop_holographic": {
    "id": "device_emblem_cyberpunk_du_laptop_holographic",
    "category": "07-physical-world",
    "png": "/assets/production/07-physical-world/device_emblem_cyberpunk_du_laptop_holographic.png",
    "webp": "/assets/web/07-physical-world/device_emblem_cyberpunk_du_laptop_holographic.webp",
    "thumbnail": "/assets/thumbnails/07-physical-world/device_emblem_cyberpunk_du_laptop_holographic.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "device",
      "physical-world",
      "connected"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "agent_emblem_de_cybersecurity_holographic": {
    "id": "agent_emblem_de_cybersecurity_holographic",
    "category": "06-agents",
    "png": "/assets/production/06-agents/agent_emblem_de_cybersecurity_holographic.png",
    "webp": "/assets/web/06-agents/agent_emblem_de_cybersecurity_holographic.webp",
    "thumbnail": "/assets/thumbnails/06-agents/agent_emblem_de_cybersecurity_holographic.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "agent",
      "role",
      "identity"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "voice_emblem_futuristic_d_assistant_voice_neon": {
    "id": "voice_emblem_futuristic_d_assistant_voice_neon",
    "category": "04-voice-presence",
    "png": "/assets/production/04-voice-presence/voice_emblem_futuristic_d_assistant_voice_neon.png",
    "webp": "/assets/web/04-voice-presence/voice_emblem_futuristic_d_assistant_voice_neon.webp",
    "thumbnail": "/assets/thumbnails/04-voice-presence/voice_emblem_futuristic_d_assistant_voice_neon.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "voice",
      "hands-free",
      "presence"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "state_emblem_holographic_cyberpunk_en_pause": {
    "id": "state_emblem_holographic_cyberpunk_en_pause",
    "category": "08-actions-states",
    "png": "/assets/production/08-actions-states/state_emblem_holographic_cyberpunk_en_pause.png",
    "webp": "/assets/web/08-actions-states/state_emblem_holographic_cyberpunk_en_pause.webp",
    "thumbnail": "/assets/thumbnails/08-actions-states/state_emblem_holographic_cyberpunk_en_pause.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "state",
      "action",
      "status"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "state_emblem_holographic_d_alert_futuristic": {
    "id": "state_emblem_holographic_d_alert_futuristic",
    "category": "08-actions-states",
    "png": "/assets/production/08-actions-states/state_emblem_holographic_d_alert_futuristic.png",
    "webp": "/assets/web/08-actions-states/state_emblem_holographic_d_alert_futuristic.webp",
    "thumbnail": "/assets/thumbnails/08-actions-states/state_emblem_holographic_d_alert_futuristic.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "state",
      "action",
      "status"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "device_emblem_holographic_de_camera_cybernetique": {
    "id": "device_emblem_holographic_de_camera_cybernetique",
    "category": "07-physical-world",
    "png": "/assets/production/07-physical-world/device_emblem_holographic_de_camera_cybernetique.png",
    "webp": "/assets/web/07-physical-world/device_emblem_holographic_de_camera_cybernetique.webp",
    "thumbnail": "/assets/thumbnails/07-physical-world/device_emblem_holographic_de_camera_cybernetique.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "device",
      "physical-world",
      "connected"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "agent_emblem_holographic_de_communication_ia": {
    "id": "agent_emblem_holographic_de_communication_ia",
    "category": "06-agents",
    "png": "/assets/production/06-agents/agent_emblem_holographic_de_communication_ia.png",
    "webp": "/assets/web/06-agents/agent_emblem_holographic_de_communication_ia.webp",
    "thumbnail": "/assets/thumbnails/06-agents/agent_emblem_holographic_de_communication_ia.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "agent",
      "role",
      "identity"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "memory_emblem_holographic_de_control_ia": {
    "id": "memory_emblem_holographic_de_control_ia",
    "category": "05-memory-intelligence",
    "png": "/assets/production/05-memory-intelligence/memory_emblem_holographic_de_control_ia.png",
    "webp": "/assets/web/05-memory-intelligence/memory_emblem_holographic_de_control_ia.webp",
    "thumbnail": "/assets/thumbnails/05-memory-intelligence/memory_emblem_holographic_de_control_ia.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "memory",
      "intelligence",
      "context"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "agent_emblem_holographic_de_creation_futuristic": {
    "id": "agent_emblem_holographic_de_creation_futuristic",
    "category": "06-agents",
    "png": "/assets/production/06-agents/agent_emblem_holographic_de_creation_futuristic.png",
    "webp": "/assets/web/06-agents/agent_emblem_holographic_de_creation_futuristic.webp",
    "thumbnail": "/assets/thumbnails/06-agents/agent_emblem_holographic_de_creation_futuristic.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "agent",
      "role",
      "identity"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "device_emblem_holographic_de_smart_home": {
    "id": "device_emblem_holographic_de_smart_home",
    "category": "07-physical-world",
    "png": "/assets/production/07-physical-world/device_emblem_holographic_de_smart_home.png",
    "webp": "/assets/web/07-physical-world/device_emblem_holographic_de_smart_home.webp",
    "thumbnail": "/assets/thumbnails/07-physical-world/device_emblem_holographic_de_smart_home.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "device",
      "physical-world",
      "connected"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "voice_emblem_holographic_de_microphonephone_neon": {
    "id": "voice_emblem_holographic_de_microphonephone_neon",
    "category": "04-voice-presence",
    "png": "/assets/production/04-voice-presence/voice_emblem_holographic_de_microphonephone_neon.png",
    "webp": "/assets/web/04-voice-presence/voice_emblem_holographic_de_microphonephone_neon.webp",
    "thumbnail": "/assets/thumbnails/04-voice-presence/voice_emblem_holographic_de_microphonephone_neon.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "voice",
      "hands-free",
      "presence"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "agent_emblem_holographic_de_protection_cybernetique": {
    "id": "agent_emblem_holographic_de_protection_cybernetique",
    "category": "06-agents",
    "png": "/assets/production/06-agents/agent_emblem_holographic_de_protection_cybernetique.png",
    "webp": "/assets/web/06-agents/agent_emblem_holographic_de_protection_cybernetique.webp",
    "thumbnail": "/assets/thumbnails/06-agents/agent_emblem_holographic_de_protection_cybernetique.webp",
    "width": 1536,
    "height": 1024,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "agent",
      "role",
      "identity"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "state_emblem_holographic_de_download_futuristic": {
    "id": "state_emblem_holographic_de_download_futuristic",
    "category": "08-actions-states",
    "png": "/assets/production/08-actions-states/state_emblem_holographic_de_download_futuristic.png",
    "webp": "/assets/web/08-actions-states/state_emblem_holographic_de_download_futuristic.webp",
    "thumbnail": "/assets/thumbnails/08-actions-states/state_emblem_holographic_de_download_futuristic.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "state",
      "action",
      "status"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "state_emblem_holographic_de_upload_cyberpunk": {
    "id": "state_emblem_holographic_de_upload_cyberpunk",
    "category": "08-actions-states",
    "png": "/assets/production/08-actions-states/state_emblem_holographic_de_upload_cyberpunk.png",
    "webp": "/assets/web/08-actions-states/state_emblem_holographic_de_upload_cyberpunk.webp",
    "thumbnail": "/assets/thumbnails/08-actions-states/state_emblem_holographic_de_upload_cyberpunk.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "state",
      "action",
      "status"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "state_emblem_holographic_de_verification_futuristic": {
    "id": "state_emblem_holographic_de_verification_futuristic",
    "category": "08-actions-states",
    "png": "/assets/production/08-actions-states/state_emblem_holographic_de_verification_futuristic.png",
    "webp": "/assets/web/08-actions-states/state_emblem_holographic_de_verification_futuristic.webp",
    "thumbnail": "/assets/thumbnails/08-actions-states/state_emblem_holographic_de_verification_futuristic.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "state",
      "action",
      "status"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "device_emblem_holographic_du_sensor_futuristic": {
    "id": "device_emblem_holographic_du_sensor_futuristic",
    "category": "07-physical-world",
    "png": "/assets/production/07-physical-world/device_emblem_holographic_du_sensor_futuristic.png",
    "webp": "/assets/web/07-physical-world/device_emblem_holographic_du_sensor_futuristic.webp",
    "thumbnail": "/assets/thumbnails/07-physical-world/device_emblem_holographic_du_sensor_futuristic.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "device",
      "physical-world",
      "connected"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "memory_emblem_holographic_du_core_memory_ia": {
    "id": "memory_emblem_holographic_du_core_memory_ia",
    "category": "05-memory-intelligence",
    "png": "/assets/production/05-memory-intelligence/memory_emblem_holographic_du_core_memory_ia.png",
    "webp": "/assets/web/05-memory-intelligence/memory_emblem_holographic_du_core_memory_ia.webp",
    "thumbnail": "/assets/thumbnails/05-memory-intelligence/memory_emblem_holographic_du_core_memory_ia.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "memory",
      "intelligence",
      "context"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "device_emblem_holographic_du_desktop_cyberpunk": {
    "id": "device_emblem_holographic_du_desktop_cyberpunk",
    "category": "07-physical-world",
    "png": "/assets/production/07-physical-world/device_emblem_holographic_du_desktop_cyberpunk.png",
    "webp": "/assets/web/07-physical-world/device_emblem_holographic_du_desktop_cyberpunk.webp",
    "thumbnail": "/assets/thumbnails/07-physical-world/device_emblem_holographic_du_desktop_cyberpunk.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "device",
      "physical-world",
      "connected"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "state_emblem_holographic_du_power_neon": {
    "id": "state_emblem_holographic_du_power_neon",
    "category": "08-actions-states",
    "png": "/assets/production/08-actions-states/state_emblem_holographic_du_power_neon.png",
    "webp": "/assets/web/08-actions-states/state_emblem_holographic_du_power_neon.webp",
    "thumbnail": "/assets/thumbnails/08-actions-states/state_emblem_holographic_du_power_neon.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "state",
      "action",
      "status"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "memory_emblem_neon_d_analysis_spatial": {
    "id": "memory_emblem_neon_d_analysis_spatial",
    "category": "05-memory-intelligence",
    "png": "/assets/production/05-memory-intelligence/memory_emblem_neon_d_analysis_spatial.png",
    "webp": "/assets/web/05-memory-intelligence/memory_emblem_neon_d_analysis_spatial.webp",
    "thumbnail": "/assets/thumbnails/05-memory-intelligence/memory_emblem_neon_d_analysis_spatial.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "memory",
      "intelligence",
      "context"
    ],
    "issues": []
  },
  "capability_emblem_neon_d_automation_futuristic": {
    "id": "capability_emblem_neon_d_automation_futuristic",
    "category": "02-system-capabilities",
    "png": "/assets/production/02-system-capabilities/capability_emblem_neon_d_automation_futuristic.png",
    "webp": "/assets/web/02-system-capabilities/capability_emblem_neon_d_automation_futuristic.webp",
    "thumbnail": "/assets/thumbnails/02-system-capabilities/capability_emblem_neon_d_automation_futuristic.webp",
    "width": 1536,
    "height": 1024,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "capability",
      "system"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "state_emblem_neon_de_sync_futuristic": {
    "id": "state_emblem_neon_de_sync_futuristic",
    "category": "08-actions-states",
    "png": "/assets/production/08-actions-states/state_emblem_neon_de_sync_futuristic.png",
    "webp": "/assets/web/08-actions-states/state_emblem_neon_de_sync_futuristic.webp",
    "thumbnail": "/assets/thumbnails/08-actions-states/state_emblem_neon_de_sync_futuristic.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "state",
      "action",
      "status"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "core_emblem_orbital_quantum_lumineux": {
    "id": "core_emblem_orbital_quantum_lumineux",
    "category": "01-core-system",
    "png": "/assets/production/01-core-system/core_emblem_orbital_quantum_lumineux.png",
    "webp": "/assets/web/01-core-system/core_emblem_orbital_quantum_lumineux.webp",
    "thumbnail": "/assets/thumbnails/01-core-system/core_emblem_orbital_quantum_lumineux.webp",
    "width": 1536,
    "height": 1024,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "core",
      "system",
      "hero"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "device_emblem_satellite_holographic_futuristic": {
    "id": "device_emblem_satellite_holographic_futuristic",
    "category": "07-physical-world",
    "png": "/assets/production/07-physical-world/device_emblem_satellite_holographic_futuristic.png",
    "webp": "/assets/web/07-physical-world/device_emblem_satellite_holographic_futuristic.webp",
    "thumbnail": "/assets/thumbnails/07-physical-world/device_emblem_satellite_holographic_futuristic.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "device",
      "physical-world",
      "connected"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "device_emblem_smartphone_orbital_neon_futuristic": {
    "id": "device_emblem_smartphone_orbital_neon_futuristic",
    "category": "07-physical-world",
    "png": "/assets/production/07-physical-world/device_emblem_smartphone_orbital_neon_futuristic.png",
    "webp": "/assets/web/07-physical-world/device_emblem_smartphone_orbital_neon_futuristic.webp",
    "thumbnail": "/assets/thumbnails/07-physical-world/device_emblem_smartphone_orbital_neon_futuristic.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "device",
      "physical-world",
      "connected"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "core_globe_holographic_neon_futuristic": {
    "id": "core_globe_holographic_neon_futuristic",
    "category": "01-core-system",
    "png": "/assets/production/01-core-system/core_globe_holographic_neon_futuristic.png",
    "webp": "/assets/web/01-core-system/core_globe_holographic_neon_futuristic.webp",
    "thumbnail": "/assets/thumbnails/01-core-system/core_globe_holographic_neon_futuristic.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "core",
      "system",
      "hero"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "scene_hangar_futuristic_de_drones_en_orbit": {
    "id": "scene_hangar_futuristic_de_drones_en_orbit",
    "category": "09-cinematic-environments",
    "png": "/assets/production/09-cinematic-environments/scene_hangar_futuristic_de_drones_en_orbit.png",
    "webp": "/assets/web/09-cinematic-environments/scene_hangar_futuristic_de_drones_en_orbit.webp",
    "thumbnail": "/assets/thumbnails/09-cinematic-environments/scene_hangar_futuristic_de_drones_en_orbit.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "cinematic",
      "environment",
      "scene"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "voice_icon_holographic_de_microphone_permission": {
    "id": "voice_icon_holographic_de_microphone_permission",
    "category": "04-voice-presence",
    "png": "/assets/production/04-voice-presence/voice_icon_holographic_de_microphone_permission.png",
    "webp": "/assets/web/04-voice-presence/voice_icon_holographic_de_microphone_permission.webp",
    "thumbnail": "/assets/thumbnails/04-voice-presence/voice_icon_holographic_de_microphone_permission.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "voice",
      "hands-free",
      "presence"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "scene_secure_data_vault_environment": {
    "id": "scene_secure_data_vault_environment",
    "category": "09-cinematic-environments",
    "png": "/assets/production/09-cinematic-environments/scene_secure_data_vault_environment.png",
    "webp": "/assets/web/09-cinematic-environments/scene_secure_data_vault_environment.webp",
    "thumbnail": "/assets/thumbnails/09-cinematic-environments/scene_secure_data_vault_environment.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "cinematic",
      "environment",
      "secure-vault",
      "data"
    ],
    "issues": []
  },
  "ui_interface_de_research_futuristic_jarvis_x2": {
    "id": "ui_interface_de_research_futuristic_jarvis_x2",
    "category": "03-product-ui",
    "png": "/assets/production/03-product-ui/ui_interface_de_research_futuristic_jarvis_x2.png",
    "webp": "/assets/web/03-product-ui/ui_interface_de_research_futuristic_jarvis_x2.webp",
    "thumbnail": "/assets/thumbnails/03-product-ui/ui_interface_de_research_futuristic_jarvis_x2.webp",
    "width": 1024,
    "height": 1536,
    "hasAlpha": false,
    "grade": "B",
    "status": "review",
    "tags": [
      "ui",
      "dashboard",
      "product"
    ],
    "issues": []
  },
  "state_interface_holographic_d_approval_futuristic": {
    "id": "state_interface_holographic_d_approval_futuristic",
    "category": "08-actions-states",
    "png": "/assets/production/08-actions-states/state_interface_holographic_d_approval_futuristic.png",
    "webp": "/assets/web/08-actions-states/state_interface_holographic_d_approval_futuristic.webp",
    "thumbnail": "/assets/thumbnails/08-actions-states/state_interface_holographic_d_approval_futuristic.webp",
    "width": 1024,
    "height": 1536,
    "hasAlpha": false,
    "grade": "B",
    "status": "review",
    "tags": [
      "state",
      "action",
      "status"
    ],
    "issues": [
      "opaque background; use as scene/card, not floating asset"
    ]
  },
  "ui_interface_holographic_de_secure_vault": {
    "id": "ui_interface_holographic_de_secure_vault",
    "category": "03-product-ui",
    "png": "/assets/production/03-product-ui/ui_interface_holographic_de_secure_vault.png",
    "webp": "/assets/web/03-product-ui/ui_interface_holographic_de_secure_vault.webp",
    "thumbnail": "/assets/thumbnails/03-product-ui/ui_interface_holographic_de_secure_vault.webp",
    "width": 1024,
    "height": 1536,
    "hasAlpha": false,
    "grade": "B",
    "status": "review",
    "tags": [
      "ui",
      "dashboard",
      "product"
    ],
    "issues": []
  },
  "ui_interface_holographic_focus_deep_work": {
    "id": "ui_interface_holographic_focus_deep_work",
    "category": "03-product-ui",
    "png": "/assets/production/03-product-ui/ui_interface_holographic_focus_deep_work.png",
    "webp": "/assets/web/03-product-ui/ui_interface_holographic_focus_deep_work.webp",
    "thumbnail": "/assets/thumbnails/03-product-ui/ui_interface_holographic_focus_deep_work.webp",
    "width": 1024,
    "height": 1536,
    "hasAlpha": false,
    "grade": "B",
    "status": "review",
    "tags": [
      "ui",
      "dashboard",
      "product"
    ],
    "issues": []
  },
  "ui_interface_holographic_jarvis_x2": {
    "id": "ui_interface_holographic_jarvis_x2",
    "category": "03-product-ui",
    "png": "/assets/production/03-product-ui/ui_interface_holographic_jarvis_x2.png",
    "webp": "/assets/web/03-product-ui/ui_interface_holographic_jarvis_x2.webp",
    "thumbnail": "/assets/thumbnails/03-product-ui/ui_interface_holographic_jarvis_x2.webp",
    "width": 1024,
    "height": 1536,
    "hasAlpha": false,
    "grade": "B",
    "status": "review",
    "tags": [
      "ui",
      "dashboard",
      "product"
    ],
    "issues": []
  },
  "memory_interface_holographic_knowledge_futuristic": {
    "id": "memory_interface_holographic_knowledge_futuristic",
    "category": "05-memory-intelligence",
    "png": "/assets/production/05-memory-intelligence/memory_interface_holographic_knowledge_futuristic.png",
    "webp": "/assets/web/05-memory-intelligence/memory_interface_holographic_knowledge_futuristic.webp",
    "thumbnail": "/assets/thumbnails/05-memory-intelligence/memory_interface_holographic_knowledge_futuristic.webp",
    "width": 1024,
    "height": 1536,
    "hasAlpha": false,
    "grade": "B",
    "status": "review",
    "tags": [
      "memory",
      "intelligence",
      "context"
    ],
    "issues": [
      "opaque background; use as scene/card, not floating asset"
    ]
  },
  "capability_jarvis_x2_local_ai_futuristic": {
    "id": "capability_jarvis_x2_local_ai_futuristic",
    "category": "02-system-capabilities",
    "png": "/assets/production/02-system-capabilities/capability_jarvis_x2_local_ai_futuristic.png",
    "webp": "/assets/web/02-system-capabilities/capability_jarvis_x2_local_ai_futuristic.webp",
    "thumbnail": "/assets/thumbnails/02-system-capabilities/capability_jarvis_x2_local_ai_futuristic.webp",
    "width": 1672,
    "height": 941,
    "hasAlpha": false,
    "grade": "B",
    "status": "review",
    "tags": [
      "system",
      "general"
    ],
    "issues": [
      "opaque background; use as scene/card, not floating asset"
    ]
  },
  "device_wearable_holographic_futuristic": {
    "id": "device_wearable_holographic_futuristic",
    "category": "07-physical-world",
    "png": "/assets/production/07-physical-world/device_wearable_holographic_futuristic.png",
    "webp": "/assets/web/07-physical-world/device_wearable_holographic_futuristic.webp",
    "thumbnail": "/assets/thumbnails/07-physical-world/device_wearable_holographic_futuristic.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "device",
      "physical-world",
      "connected"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "scene_metropolis_cyberpunk_flottante_neon": {
    "id": "scene_metropolis_cyberpunk_flottante_neon",
    "category": "09-cinematic-environments",
    "png": "/assets/production/09-cinematic-environments/scene_metropolis_cyberpunk_flottante_neon.png",
    "webp": "/assets/web/09-cinematic-environments/scene_metropolis_cyberpunk_flottante_neon.webp",
    "thumbnail": "/assets/thumbnails/09-cinematic-environments/scene_metropolis_cyberpunk_flottante_neon.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "cinematic",
      "environment",
      "scene"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "core_nexus_cosmic_holographic_neon": {
    "id": "core_nexus_cosmic_holographic_neon",
    "category": "01-core-system",
    "png": "/assets/production/01-core-system/core_nexus_cosmic_holographic_neon.png",
    "webp": "/assets/web/01-core-system/core_nexus_cosmic_holographic_neon.webp",
    "thumbnail": "/assets/thumbnails/01-core-system/core_nexus_cosmic_holographic_neon.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "core",
      "system",
      "hero"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "core_nexus_holographic_orbital_futuristic": {
    "id": "core_nexus_holographic_orbital_futuristic",
    "category": "01-core-system",
    "png": "/assets/production/01-core-system/core_nexus_holographic_orbital_futuristic.png",
    "webp": "/assets/web/01-core-system/core_nexus_holographic_orbital_futuristic.webp",
    "thumbnail": "/assets/thumbnails/01-core-system/core_nexus_holographic_orbital_futuristic.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "core",
      "system",
      "hero"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "scene_nexus_energy_futuristic_en_orbit": {
    "id": "scene_nexus_energy_futuristic_en_orbit",
    "category": "09-cinematic-environments",
    "png": "/assets/production/09-cinematic-environments/scene_nexus_energy_futuristic_en_orbit.png",
    "webp": "/assets/web/09-cinematic-environments/scene_nexus_energy_futuristic_en_orbit.webp",
    "thumbnail": "/assets/thumbnails/09-cinematic-environments/scene_nexus_energy_futuristic_en_orbit.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "cinematic",
      "environment",
      "scene"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "voice_core_d_energy_audio_futuristic_symmetric": {
    "id": "voice_core_d_energy_audio_futuristic_symmetric",
    "category": "04-voice-presence",
    "png": "/assets/production/04-voice-presence/voice_core_d_energy_audio_futuristic_symmetric.png",
    "webp": "/assets/web/04-voice-presence/voice_core_d_energy_audio_futuristic_symmetric.webp",
    "thumbnail": "/assets/thumbnails/04-voice-presence/voice_core_d_energy_audio_futuristic_symmetric.webp",
    "width": 1536,
    "height": 1024,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "voice",
      "hands-free",
      "presence"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "core_d_energy_holographic_futuristic": {
    "id": "core_d_energy_holographic_futuristic",
    "category": "01-core-system",
    "png": "/assets/production/01-core-system/core_d_energy_holographic_futuristic.png",
    "webp": "/assets/web/01-core-system/core_d_energy_holographic_futuristic.webp",
    "thumbnail": "/assets/thumbnails/01-core-system/core_d_energy_holographic_futuristic.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "core",
      "system",
      "hero"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "memory_core_de_data_holographic_futuristic": {
    "id": "memory_core_de_data_holographic_futuristic",
    "category": "05-memory-intelligence",
    "png": "/assets/production/05-memory-intelligence/memory_core_de_data_holographic_futuristic.png",
    "webp": "/assets/web/05-memory-intelligence/memory_core_de_data_holographic_futuristic.webp",
    "thumbnail": "/assets/thumbnails/05-memory-intelligence/memory_core_de_data_holographic_futuristic.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "memory",
      "intelligence",
      "context"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "core_holographic_d_energy_futuristic": {
    "id": "core_holographic_d_energy_futuristic",
    "category": "01-core-system",
    "png": "/assets/production/01-core-system/core_holographic_d_energy_futuristic.png",
    "webp": "/assets/web/01-core-system/core_holographic_d_energy_futuristic.webp",
    "thumbnail": "/assets/thumbnails/01-core-system/core_holographic_d_energy_futuristic.webp",
    "width": 1536,
    "height": 1024,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "core",
      "system",
      "hero"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "core_nebula_d_energy_cosmic_neon": {
    "id": "core_nebula_d_energy_cosmic_neon",
    "category": "01-core-system",
    "png": "/assets/production/01-core-system/core_nebula_d_energy_cosmic_neon.png",
    "webp": "/assets/web/01-core-system/core_nebula_d_energy_cosmic_neon.webp",
    "thumbnail": "/assets/thumbnails/01-core-system/core_nebula_d_energy_cosmic_neon.webp",
    "width": 1536,
    "height": 1024,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "core",
      "system",
      "hero"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "device_nud_quantum_iot_en_orbit": {
    "id": "device_nud_quantum_iot_en_orbit",
    "category": "07-physical-world",
    "png": "/assets/production/07-physical-world/device_nud_quantum_iot_en_orbit.png",
    "webp": "/assets/web/07-physical-world/device_nud_quantum_iot_en_orbit.webp",
    "thumbnail": "/assets/thumbnails/07-physical-world/device_nud_quantum_iot_en_orbit.webp",
    "width": 1536,
    "height": 1024,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "device",
      "physical-world",
      "connected"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "voice_orbe_d_alert_voicee_cybernetique": {
    "id": "voice_orbe_d_alert_voicee_cybernetique",
    "category": "04-voice-presence",
    "png": "/assets/production/04-voice-presence/voice_orbe_d_alert_voicee_cybernetique.png",
    "webp": "/assets/web/04-voice-presence/voice_orbe_d_alert_voicee_cybernetique.webp",
    "thumbnail": "/assets/thumbnails/04-voice-presence/voice_orbe_d_alert_voicee_cybernetique.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "voice",
      "hands-free",
      "presence"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "memory_orbe_holographic_d_ai": {
    "id": "memory_orbe_holographic_d_ai",
    "category": "05-memory-intelligence",
    "png": "/assets/production/05-memory-intelligence/memory_orbe_holographic_d_ai.png",
    "webp": "/assets/web/05-memory-intelligence/memory_orbe_holographic_d_ai.webp",
    "thumbnail": "/assets/thumbnails/05-memory-intelligence/memory_orbe_holographic_d_ai.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "memory",
      "intelligence",
      "context"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "core_orbe_hud_futuristic_neon_sur_transparence": {
    "id": "core_orbe_hud_futuristic_neon_sur_transparence",
    "category": "01-core-system",
    "png": "/assets/production/01-core-system/core_orbe_hud_futuristic_neon_sur_transparence.png",
    "webp": "/assets/web/01-core-system/core_orbe_hud_futuristic_neon_sur_transparence.webp",
    "thumbnail": "/assets/thumbnails/01-core-system/core_orbe_hud_futuristic_neon_sur_transparence.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "core",
      "system",
      "hero"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "core_orbe_energy_holographic_futuristic": {
    "id": "core_orbe_energy_holographic_futuristic",
    "category": "01-core-system",
    "png": "/assets/production/01-core-system/core_orbe_energy_holographic_futuristic.png",
    "webp": "/assets/web/01-core-system/core_orbe_energy_holographic_futuristic.webp",
    "thumbnail": "/assets/thumbnails/01-core-system/core_orbe_energy_holographic_futuristic.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "core",
      "system",
      "hero"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "state_panel_hud_futuristic_de_task_progress": {
    "id": "state_panel_hud_futuristic_de_task_progress",
    "category": "08-actions-states",
    "png": "/assets/production/08-actions-states/state_panel_hud_futuristic_de_task_progress.png",
    "webp": "/assets/web/08-actions-states/state_panel_hud_futuristic_de_task_progress.webp",
    "thumbnail": "/assets/thumbnails/08-actions-states/state_panel_hud_futuristic_de_task_progress.webp",
    "width": 1024,
    "height": 1536,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "state",
      "action",
      "status"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "scene_platform_energy_futuristic_en_levitation": {
    "id": "scene_platform_energy_futuristic_en_levitation",
    "category": "09-cinematic-environments",
    "png": "/assets/production/09-cinematic-environments/scene_platform_energy_futuristic_en_levitation.png",
    "webp": "/assets/web/09-cinematic-environments/scene_platform_energy_futuristic_en_levitation.webp",
    "thumbnail": "/assets/thumbnails/09-cinematic-environments/scene_platform_energy_futuristic_en_levitation.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "cinematic",
      "environment",
      "scene"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "scene_command_bridge_spatial_holographic": {
    "id": "scene_command_bridge_spatial_holographic",
    "category": "09-cinematic-environments",
    "png": "/assets/production/09-cinematic-environments/scene_command_bridge_spatial_holographic.png",
    "webp": "/assets/web/09-cinematic-environments/scene_command_bridge_spatial_holographic.webp",
    "thumbnail": "/assets/thumbnails/09-cinematic-environments/scene_command_bridge_spatial_holographic.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "cinematic",
      "environment",
      "scene"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "scene_portal_cosmic_futuristic_aux_crystals_lumineux": {
    "id": "scene_portal_cosmic_futuristic_aux_crystals_lumineux",
    "category": "09-cinematic-environments",
    "png": "/assets/production/09-cinematic-environments/scene_portal_cosmic_futuristic_aux_crystals_lumineux.png",
    "webp": "/assets/web/09-cinematic-environments/scene_portal_cosmic_futuristic_aux_crystals_lumineux.webp",
    "thumbnail": "/assets/thumbnails/09-cinematic-environments/scene_portal_cosmic_futuristic_aux_crystals_lumineux.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "cinematic",
      "environment",
      "scene"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "core_portal_holographic_neon_symmetric": {
    "id": "core_portal_holographic_neon_symmetric",
    "category": "01-core-system",
    "png": "/assets/production/01-core-system/core_portal_holographic_neon_symmetric.png",
    "webp": "/assets/web/01-core-system/core_portal_holographic_neon_symmetric.webp",
    "thumbnail": "/assets/thumbnails/01-core-system/core_portal_holographic_neon_symmetric.webp",
    "width": 1536,
    "height": 1024,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "core",
      "system",
      "hero"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "capability_portal_energy_futuristic_bleu_et_violet": {
    "id": "capability_portal_energy_futuristic_bleu_et_violet",
    "category": "02-system-capabilities",
    "png": "/assets/production/02-system-capabilities/capability_portal_energy_futuristic_bleu_et_violet.png",
    "webp": "/assets/web/02-system-capabilities/capability_portal_energy_futuristic_bleu_et_violet.webp",
    "thumbnail": "/assets/thumbnails/02-system-capabilities/capability_portal_energy_futuristic_bleu_et_violet.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "system",
      "general"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "scene_reactor_holographic_futuristic_en_levitation": {
    "id": "scene_reactor_holographic_futuristic_en_levitation",
    "category": "09-cinematic-environments",
    "png": "/assets/production/09-cinematic-environments/scene_reactor_holographic_futuristic_en_levitation.png",
    "webp": "/assets/web/09-cinematic-environments/scene_reactor_holographic_futuristic_en_levitation.webp",
    "thumbnail": "/assets/thumbnails/09-cinematic-environments/scene_reactor_holographic_futuristic_en_levitation.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "cinematic",
      "environment",
      "scene"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "memory_holographic_network_d_ai": {
    "id": "memory_holographic_network_d_ai",
    "category": "05-memory-intelligence",
    "png": "/assets/production/05-memory-intelligence/memory_holographic_network_d_ai.png",
    "webp": "/assets/web/05-memory-intelligence/memory_holographic_network_d_ai.webp",
    "thumbnail": "/assets/thumbnails/05-memory-intelligence/memory_holographic_network_d_ai.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "memory",
      "intelligence",
      "context"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "memory_neural_network_holographic_neon": {
    "id": "memory_neural_network_holographic_neon",
    "category": "05-memory-intelligence",
    "png": "/assets/production/05-memory-intelligence/memory_neural_network_holographic_neon.png",
    "webp": "/assets/web/05-memory-intelligence/memory_neural_network_holographic_neon.webp",
    "thumbnail": "/assets/thumbnails/05-memory-intelligence/memory_neural_network_holographic_neon.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "memory",
      "intelligence",
      "context"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "scene_vr_lounge_futuristic_holographic_luxueux": {
    "id": "scene_vr_lounge_futuristic_holographic_luxueux",
    "category": "09-cinematic-environments",
    "png": "/assets/production/09-cinematic-environments/scene_vr_lounge_futuristic_holographic_luxueux.png",
    "webp": "/assets/web/09-cinematic-environments/scene_vr_lounge_futuristic_holographic_luxueux.webp",
    "thumbnail": "/assets/thumbnails/09-cinematic-environments/scene_vr_lounge_futuristic_holographic_luxueux.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "cinematic",
      "environment",
      "scene"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "capability_sphere_holographic_de_management_documents": {
    "id": "capability_sphere_holographic_de_management_documents",
    "category": "02-system-capabilities",
    "png": "/assets/production/02-system-capabilities/capability_sphere_holographic_de_management_documents.png",
    "webp": "/assets/web/02-system-capabilities/capability_sphere_holographic_de_management_documents.webp",
    "thumbnail": "/assets/thumbnails/02-system-capabilities/capability_sphere_holographic_de_management_documents.webp",
    "width": 1254,
    "height": 1254,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "system",
      "general"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "ui_dashboard_d_automation_futuristic": {
    "id": "ui_dashboard_d_automation_futuristic",
    "category": "03-product-ui",
    "png": "/assets/production/03-product-ui/ui_dashboard_d_automation_futuristic.png",
    "webp": "/assets/web/03-product-ui/ui_dashboard_d_automation_futuristic.webp",
    "thumbnail": "/assets/thumbnails/03-product-ui/ui_dashboard_d_automation_futuristic.webp",
    "width": 1024,
    "height": 1536,
    "hasAlpha": false,
    "grade": "B",
    "status": "review",
    "tags": [
      "ui",
      "dashboard",
      "product"
    ],
    "issues": []
  },
  "ui_dashboard_futuristic_jarvis_x2": {
    "id": "ui_dashboard_futuristic_jarvis_x2",
    "category": "03-product-ui",
    "png": "/assets/production/03-product-ui/ui_dashboard_futuristic_jarvis_x2.png",
    "webp": "/assets/web/03-product-ui/ui_dashboard_futuristic_jarvis_x2.webp",
    "thumbnail": "/assets/thumbnails/03-product-ui/ui_dashboard_futuristic_jarvis_x2.webp",
    "width": 1024,
    "height": 1536,
    "hasAlpha": false,
    "grade": "B",
    "status": "review",
    "tags": [
      "ui",
      "dashboard",
      "product"
    ],
    "issues": []
  },
  "ui_dashboard_holographic_analytics": {
    "id": "ui_dashboard_holographic_analytics",
    "category": "03-product-ui",
    "png": "/assets/production/03-product-ui/ui_dashboard_holographic_analytics.png",
    "webp": "/assets/web/03-product-ui/ui_dashboard_holographic_analytics.webp",
    "thumbnail": "/assets/thumbnails/03-product-ui/ui_dashboard_holographic_analytics.webp",
    "width": 1024,
    "height": 1536,
    "hasAlpha": false,
    "grade": "B",
    "status": "review",
    "tags": [
      "ui",
      "dashboard",
      "product"
    ],
    "issues": []
  },
  "ui_dashboard_holographic_des_active_agents": {
    "id": "ui_dashboard_holographic_des_active_agents",
    "category": "03-product-ui",
    "png": "/assets/production/03-product-ui/ui_dashboard_holographic_des_active_agents.png",
    "webp": "/assets/web/03-product-ui/ui_dashboard_holographic_des_active_agents.webp",
    "thumbnail": "/assets/thumbnails/03-product-ui/ui_dashboard_holographic_des_active_agents.webp",
    "width": 1024,
    "height": 1536,
    "hasAlpha": false,
    "grade": "B",
    "status": "review",
    "tags": [
      "ui",
      "dashboard",
      "product"
    ],
    "issues": []
  },
  "ui_dashboard_holographic_des_documents": {
    "id": "ui_dashboard_holographic_des_documents",
    "category": "03-product-ui",
    "png": "/assets/production/03-product-ui/ui_dashboard_holographic_des_documents.png",
    "webp": "/assets/web/03-product-ui/ui_dashboard_holographic_des_documents.webp",
    "thumbnail": "/assets/thumbnails/03-product-ui/ui_dashboard_holographic_des_documents.webp",
    "width": 1024,
    "height": 1536,
    "hasAlpha": false,
    "grade": "B",
    "status": "review",
    "tags": [
      "ui",
      "dashboard",
      "product"
    ],
    "issues": []
  },
  "ui_dashboard_holographic_jarvis_x2": {
    "id": "ui_dashboard_holographic_jarvis_x2",
    "category": "03-product-ui",
    "png": "/assets/production/03-product-ui/ui_dashboard_holographic_jarvis_x2.png",
    "webp": "/assets/web/03-product-ui/ui_dashboard_holographic_jarvis_x2.webp",
    "thumbnail": "/assets/thumbnails/03-product-ui/ui_dashboard_holographic_jarvis_x2.webp",
    "width": 1024,
    "height": 1536,
    "hasAlpha": false,
    "grade": "B",
    "status": "review",
    "tags": [
      "ui",
      "dashboard",
      "product"
    ],
    "issues": []
  },
  "memory_dashboard_holographic_memory_connectee": {
    "id": "memory_dashboard_holographic_memory_connectee",
    "category": "05-memory-intelligence",
    "png": "/assets/production/05-memory-intelligence/memory_dashboard_holographic_memory_connectee.png",
    "webp": "/assets/web/05-memory-intelligence/memory_dashboard_holographic_memory_connectee.webp",
    "thumbnail": "/assets/thumbnails/05-memory-intelligence/memory_dashboard_holographic_memory_connectee.webp",
    "width": 1024,
    "height": 1536,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "memory",
      "intelligence",
      "context"
    ],
    "issues": [
      "subject touches canvas edge; verify crop at small sizes"
    ]
  },
  "ui_dashboard_jarvis_x2_dev_studio": {
    "id": "ui_dashboard_jarvis_x2_dev_studio",
    "category": "03-product-ui",
    "png": "/assets/production/03-product-ui/ui_dashboard_jarvis_x2_dev_studio.png",
    "webp": "/assets/web/03-product-ui/ui_dashboard_jarvis_x2_dev_studio.webp",
    "thumbnail": "/assets/thumbnails/03-product-ui/ui_dashboard_jarvis_x2_dev_studio.webp",
    "width": 1024,
    "height": 1536,
    "hasAlpha": false,
    "grade": "B",
    "status": "review",
    "tags": [
      "ui",
      "dashboard",
      "product"
    ],
    "issues": []
  },
  "capability_tableau_de_navigation_holographic_futuristic": {
    "id": "capability_tableau_de_navigation_holographic_futuristic",
    "category": "02-system-capabilities",
    "png": "/assets/production/02-system-capabilities/capability_tableau_de_navigation_holographic_futuristic.png",
    "webp": "/assets/web/02-system-capabilities/capability_tableau_de_navigation_holographic_futuristic.webp",
    "thumbnail": "/assets/thumbnails/02-system-capabilities/capability_tableau_de_navigation_holographic_futuristic.webp",
    "width": 1024,
    "height": 1536,
    "hasAlpha": false,
    "grade": "B",
    "status": "review",
    "tags": [
      "capability",
      "system"
    ],
    "issues": [
      "opaque background; use as scene/card, not floating asset"
    ]
  },
  "capability_tableau_weather_futuristic_de_location": {
    "id": "capability_tableau_weather_futuristic_de_location",
    "category": "02-system-capabilities",
    "png": "/assets/production/02-system-capabilities/capability_tableau_weather_futuristic_de_location.png",
    "webp": "/assets/web/02-system-capabilities/capability_tableau_weather_futuristic_de_location.webp",
    "thumbnail": "/assets/thumbnails/02-system-capabilities/capability_tableau_weather_futuristic_de_location.webp",
    "width": 1024,
    "height": 1536,
    "hasAlpha": true,
    "grade": "A",
    "status": "approved",
    "tags": [
      "capability",
      "system"
    ],
    "issues": []
  }
} as const;

export const ASSET_IDS = Object.keys(ASSET_REGISTRY) as AssetId[];

export function getAsset(id: AssetId): AssetEntry {
  return ASSET_REGISTRY[id];
}
